/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/account/center/': RouteRecordInfo<
      '/account/center/',
      '/account/center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/settings/': RouteRecordInfo<
      '/account/settings/',
      '/account/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Analysis': RouteRecordInfo<
      'Analysis',
      '/dashboard/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/workbench/': RouteRecordInfo<
      '/dashboard/workbench/',
      '/dashboard/workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/table-pagination-test': RouteRecordInfo<
      '/demo/table-pagination-test',
      '/demo/table-pagination-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/503': RouteRecordInfo<
      '/error/503',
      '/error/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/micro-app/SubAppView': RouteRecordInfo<
      '/micro-app/SubAppView',
      '/micro-app/SubAppView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ScreenMonitor': RouteRecordInfo<
      'ScreenMonitor',
      '/screen/monitor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/security/dashboard/': RouteRecordInfo<
      '/security/dashboard/',
      '/security/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/': RouteRecordInfo<
      '/system/dict/',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/file/': RouteRecordInfo<
      '/system/file/',
      '/system/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/log/': RouteRecordInfo<
      '/system/log/',
      '/system/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/login-log/': RouteRecordInfo<
      '/system/login-log/',
      '/system/login-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/micro-app/': RouteRecordInfo<
      '/system/micro-app/',
      '/system/micro-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/notice/': RouteRecordInfo<
      '/system/notice/',
      '/system/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/online/': RouteRecordInfo<
      '/system/online/',
      '/system/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/post/': RouteRecordInfo<
      '/system/post/',
      '/system/post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/': RouteRecordInfo<
      '/system/settings/',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/account/center/index.vue': {
      routes:
        | '/account/center/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/account/settings/index.vue': {
      routes:
        | '/account/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/analysis/index.vue': {
      routes:
        | 'Analysis'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/workbench/index.vue': {
      routes:
        | '/dashboard/workbench/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/demo/table-pagination-test.vue': {
      routes:
        | '/demo/table-pagination-test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/503.vue': {
      routes:
        | '/error/503'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/micro-app/SubAppView.vue': {
      routes:
        | '/micro-app/SubAppView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/screen/monitor/index.vue': {
      routes:
        | 'ScreenMonitor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/security/dashboard/index.vue': {
      routes:
        | '/security/dashboard/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/dict/index.vue': {
      routes:
        | '/system/dict/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/file/index.vue': {
      routes:
        | '/system/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/log/index.vue': {
      routes:
        | '/system/log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/login-log/index.vue': {
      routes:
        | '/system/login-log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/micro-app/index.vue': {
      routes:
        | '/system/micro-app/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/notice/index.vue': {
      routes:
        | '/system/notice/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/online/index.vue': {
      routes:
        | '/system/online/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/post/index.vue': {
      routes:
        | '/system/post/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/settings/index.vue': {
      routes:
        | '/system/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
