/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADivider: typeof import('antdv-next')['Divider']
    ADrawer: typeof import('antdv-next')['Drawer']
    AEmpty: typeof import('antdv-next')['Empty']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    AModal: typeof import('antdv-next')['Modal']
    APopconfirm: typeof import('antdv-next')['Popconfirm']
    ARow: typeof import('antdv-next')['Row']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASpace: typeof import('antdv-next')['Space']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATooltip: typeof import('antdv-next')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AAvatar: typeof import('antdv-next')['Avatar']
  const ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
  const AButton: typeof import('antdv-next')['Button']
  const ACard: typeof import('antdv-next')['Card']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const ACol: typeof import('antdv-next')['Col']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADescriptions: typeof import('antdv-next')['Descriptions']
  const ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
  const ADivider: typeof import('antdv-next')['Divider']
  const ADrawer: typeof import('antdv-next')['Drawer']
  const AEmpty: typeof import('antdv-next')['Empty']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputPassword: typeof import('antdv-next')['InputPassword']
  const AModal: typeof import('antdv-next')['Modal']
  const APopconfirm: typeof import('antdv-next')['Popconfirm']
  const ARow: typeof import('antdv-next')['Row']
  const ASegmented: typeof import('antdv-next')['Segmented']
  const ASpace: typeof import('antdv-next')['Space']
  const ATable: typeof import('antdv-next')['Table']
  const ATag: typeof import('antdv-next')['Tag']
  const ATooltip: typeof import('antdv-next')['Tooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}