/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/': RouteRecordInfo<
      '/account/',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analysis/': RouteRecordInfo<
      '/analysis/',
      '/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/my/': RouteRecordInfo<
      '/message/my/',
      '/message/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/notice/': RouteRecordInfo<
      '/message/notice/',
      '/message/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/todo/': RouteRecordInfo<
      '/message/todo/',
      '/message/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/micro-app/SubAppView': RouteRecordInfo<
      '/micro-app/SubAppView',
      '/micro-app/SubAppView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/cache/': RouteRecordInfo<
      '/monitor/cache/',
      '/monitor/cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/job/': RouteRecordInfo<
      '/monitor/job/',
      '/monitor/job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/log/': RouteRecordInfo<
      '/monitor/log/',
      '/monitor/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/login-log/': RouteRecordInfo<
      '/monitor/login-log/',
      '/monitor/login-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/online/': RouteRecordInfo<
      '/monitor/online/',
      '/monitor/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/server/': RouteRecordInfo<
      '/monitor/server/',
      '/monitor/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dict/': RouteRecordInfo<
      '/system/dict/',
      '/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/file/': RouteRecordInfo<
      '/system/file/',
      '/system/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/ip-rule/': RouteRecordInfo<
      '/system/ip-rule/',
      '/system/ip-rule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/micro-app/': RouteRecordInfo<
      '/system/micro-app/',
      '/system/micro-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/permission/': RouteRecordInfo<
      '/system/permission/',
      '/system/permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/post/': RouteRecordInfo<
      '/system/post/',
      '/system/post',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/': RouteRecordInfo<
      '/system/settings/',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/tenant/': RouteRecordInfo<
      '/system/tenant/',
      '/system/tenant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspace/': RouteRecordInfo<
      '/workspace/',
      '/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/account/index.vue': {
      routes:
        | '/account/'
      views:
        | never
    }
    'src/views/analysis/index.vue': {
      routes:
        | '/analysis/'
      views:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/views/message/my/index.vue': {
      routes:
        | '/message/my/'
      views:
        | never
    }
    'src/views/message/notice/index.vue': {
      routes:
        | '/message/notice/'
      views:
        | never
    }
    'src/views/message/todo/index.vue': {
      routes:
        | '/message/todo/'
      views:
        | never
    }
    'src/views/micro-app/SubAppView.vue': {
      routes:
        | '/micro-app/SubAppView'
      views:
        | never
    }
    'src/views/monitor/cache/index.vue': {
      routes:
        | '/monitor/cache/'
      views:
        | never
    }
    'src/views/monitor/job/index.vue': {
      routes:
        | '/monitor/job/'
      views:
        | never
    }
    'src/views/monitor/log/index.vue': {
      routes:
        | '/monitor/log/'
      views:
        | never
    }
    'src/views/monitor/login-log/index.vue': {
      routes:
        | '/monitor/login-log/'
      views:
        | never
    }
    'src/views/monitor/online/index.vue': {
      routes:
        | '/monitor/online/'
      views:
        | never
    }
    'src/views/monitor/server/index.vue': {
      routes:
        | '/monitor/server/'
      views:
        | never
    }
    'src/views/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/views/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
    }
    'src/views/system/dict/index.vue': {
      routes:
        | '/system/dict/'
      views:
        | never
    }
    'src/views/system/file/index.vue': {
      routes:
        | '/system/file/'
      views:
        | never
    }
    'src/views/system/ip-rule/index.vue': {
      routes:
        | '/system/ip-rule/'
      views:
        | never
    }
    'src/views/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
    }
    'src/views/system/micro-app/index.vue': {
      routes:
        | '/system/micro-app/'
      views:
        | never
    }
    'src/views/system/permission/index.vue': {
      routes:
        | '/system/permission/'
      views:
        | never
    }
    'src/views/system/post/index.vue': {
      routes:
        | '/system/post/'
      views:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/views/system/settings/index.vue': {
      routes:
        | '/system/settings/'
      views:
        | never
    }
    'src/views/system/tenant/index.vue': {
      routes:
        | '/system/tenant/'
      views:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
    }
    'src/views/workspace/index.vue': {
      routes:
        | '/workspace/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
