/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/account/': RouteRecordInfo<
      '/account/',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analysis/': RouteRecordInfo<
      '/dashboard/analysis/',
      '/dashboard/analysis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/org-history/': RouteRecordInfo<
      '/dashboard/org-history/',
      '/dashboard/org-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tenant-isolation/': RouteRecordInfo<
      '/dashboard/tenant-isolation/',
      '/dashboard/tenant-isolation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/403': RouteRecordInfo<
      '/error/403',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/404': RouteRecordInfo<
      '/error/404',
      '/error/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/error/503': RouteRecordInfo<
      '/error/503',
      '/error/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/ForgotPasswordModal': RouteRecordInfo<
      '/login/ForgotPasswordModal',
      '/login/ForgotPasswordModal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/my/': RouteRecordInfo<
      '/message/my/',
      '/message/my',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/notice/': RouteRecordInfo<
      '/message/notice/',
      '/message/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/template/': RouteRecordInfo<
      '/message/template/',
      '/message/template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/message/todo/': RouteRecordInfo<
      '/message/todo/',
      '/message/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/micro-app/SubAppView': RouteRecordInfo<
      '/micro-app/SubAppView',
      '/micro-app/SubAppView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/audit-daily/': RouteRecordInfo<
      '/monitor/audit-daily/',
      '/monitor/audit-daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/logs/': RouteRecordInfo<
      '/monitor/logs/',
      '/monitor/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/logs/log/': RouteRecordInfo<
      '/monitor/logs/log/',
      '/monitor/logs/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/logs/login-log/': RouteRecordInfo<
      '/monitor/logs/login-log/',
      '/monitor/logs/login-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/logs/logs/': RouteRecordInfo<
      '/monitor/logs/logs/',
      '/monitor/logs/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/ops/': RouteRecordInfo<
      '/monitor/ops/',
      '/monitor/ops',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/ops/backup/': RouteRecordInfo<
      '/monitor/ops/backup/',
      '/monitor/ops/backup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/ops/job/': RouteRecordInfo<
      '/monitor/ops/job/',
      '/monitor/ops/job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/ops/online/': RouteRecordInfo<
      '/monitor/ops/online/',
      '/monitor/ops/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/ops/slow-query/': RouteRecordInfo<
      '/monitor/ops/slow-query/',
      '/monitor/ops/slow-query',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/': RouteRecordInfo<
      '/monitor/runtime/',
      '/monitor/runtime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/cache/': RouteRecordInfo<
      '/monitor/runtime/cache/',
      '/monitor/runtime/cache',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/database/': RouteRecordInfo<
      '/monitor/runtime/database/',
      '/monitor/runtime/database',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/qps/': RouteRecordInfo<
      '/monitor/runtime/qps/',
      '/monitor/runtime/qps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/queue/': RouteRecordInfo<
      '/monitor/runtime/queue/',
      '/monitor/runtime/queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/runtime/server/': RouteRecordInfo<
      '/monitor/runtime/server/',
      '/monitor/runtime/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/report/dataset/': RouteRecordInfo<
      '/report/dataset/',
      '/report/dataset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/report/export-task/': RouteRecordInfo<
      '/report/export-task/',
      '/report/export-task',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/report/list/': RouteRecordInfo<
      '/report/list/',
      '/report/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/archive-policy/': RouteRecordInfo<
      '/system/archive-policy/',
      '/system/archive-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/export/': RouteRecordInfo<
      '/system/export/',
      '/system/export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/field-mask/': RouteRecordInfo<
      '/system/field-mask/',
      '/system/field-mask',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/ip-rule/': RouteRecordInfo<
      '/system/ip-rule/',
      '/system/ip-rule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/micro-app/': RouteRecordInfo<
      '/system/micro-app/',
      '/system/micro-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/org-history/': RouteRecordInfo<
      '/system/org-history/',
      '/system/org-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/permission/': RouteRecordInfo<
      '/system/permission/',
      '/system/permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/': RouteRecordInfo<
      '/system/settings/',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/storage-backend/': RouteRecordInfo<
      '/system/storage-backend/',
      '/system/storage-backend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/tenant/': RouteRecordInfo<
      '/system/tenant/',
      '/system/tenant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/tenant-isolation/': RouteRecordInfo<
      '/system/tenant-isolation/',
      '/system/tenant-isolation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user-group/': RouteRecordInfo<
      '/system/user-group/',
      '/system/user-group',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/code/': RouteRecordInfo<
      '/tool/code/',
      '/tool/code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/dict/': RouteRecordInfo<
      '/tool/dict/',
      '/tool/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/file/': RouteRecordInfo<
      '/tool/file/',
      '/tool/file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tool/gen-template/': RouteRecordInfo<
      '/tool/gen-template/',
      '/tool/gen-template',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/approval-log/': RouteRecordInfo<
      '/workflow/approval-log/',
      '/workflow/approval-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/cc/': RouteRecordInfo<
      '/workflow/cc/',
      '/workflow/cc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/center/done/': RouteRecordInfo<
      '/workflow/center/done/',
      '/workflow/center/done',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/center/initiated/': RouteRecordInfo<
      '/workflow/center/initiated/',
      '/workflow/center/initiated',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/center/todo/': RouteRecordInfo<
      '/workflow/center/todo/',
      '/workflow/center/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/definition/': RouteRecordInfo<
      '/workflow/definition/',
      '/workflow/definition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/definition/editor/': RouteRecordInfo<
      '/workflow/definition/editor/',
      '/workflow/definition/editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workflow/delegate/': RouteRecordInfo<
      '/workflow/delegate/',
      '/workflow/delegate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspace/': RouteRecordInfo<
      '/workspace/',
      '/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workspace/render': RouteRecordInfo<
      '/workspace/render',
      '/workspace/render',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/account/index.vue': {
      routes:
        | '/account/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/analysis/index.vue': {
      routes:
        | '/dashboard/analysis/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/org-history/index.vue': {
      routes:
        | '/dashboard/org-history/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/dashboard/tenant-isolation/index.vue': {
      routes:
        | '/dashboard/tenant-isolation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/403.vue': {
      routes:
        | '/error/403'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/404.vue': {
      routes:
        | '/error/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/error/503.vue': {
      routes:
        | '/error/503'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/login/ForgotPasswordModal.vue': {
      routes:
        | '/login/ForgotPasswordModal'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/message/my/index.vue': {
      routes:
        | '/message/my/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/message/notice/index.vue': {
      routes:
        | '/message/notice/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/message/template/index.vue': {
      routes:
        | '/message/template/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/message/todo/index.vue': {
      routes:
        | '/message/todo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/micro-app/SubAppView.vue': {
      routes:
        | '/micro-app/SubAppView'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/audit-daily/index.vue': {
      routes:
        | '/monitor/audit-daily/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/logs/index.vue': {
      routes:
        | '/monitor/logs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/logs/log/index.vue': {
      routes:
        | '/monitor/logs/log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/logs/login-log/index.vue': {
      routes:
        | '/monitor/logs/login-log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/logs/logs/index.vue': {
      routes:
        | '/monitor/logs/logs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/ops/index.vue': {
      routes:
        | '/monitor/ops/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/ops/backup/index.vue': {
      routes:
        | '/monitor/ops/backup/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/ops/job/index.vue': {
      routes:
        | '/monitor/ops/job/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/ops/online/index.vue': {
      routes:
        | '/monitor/ops/online/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/ops/slow-query/index.vue': {
      routes:
        | '/monitor/ops/slow-query/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/index.vue': {
      routes:
        | '/monitor/runtime/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/cache/index.vue': {
      routes:
        | '/monitor/runtime/cache/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/database/index.vue': {
      routes:
        | '/monitor/runtime/database/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/qps/index.vue': {
      routes:
        | '/monitor/runtime/qps/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/queue/index.vue': {
      routes:
        | '/monitor/runtime/queue/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/monitor/runtime/server/index.vue': {
      routes:
        | '/monitor/runtime/server/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/report/dataset/index.vue': {
      routes:
        | '/report/dataset/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/report/export-task/index.vue': {
      routes:
        | '/report/export-task/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/report/list/index.vue': {
      routes:
        | '/report/list/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/archive-policy/index.vue': {
      routes:
        | '/system/archive-policy/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/export/index.vue': {
      routes:
        | '/system/export/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/field-mask/index.vue': {
      routes:
        | '/system/field-mask/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/ip-rule/index.vue': {
      routes:
        | '/system/ip-rule/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/micro-app/index.vue': {
      routes:
        | '/system/micro-app/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/org-history/index.vue': {
      routes:
        | '/system/org-history/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/permission/index.vue': {
      routes:
        | '/system/permission/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/settings/index.vue': {
      routes:
        | '/system/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/storage-backend/index.vue': {
      routes:
        | '/system/storage-backend/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/tenant/index.vue': {
      routes:
        | '/system/tenant/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/tenant-isolation/index.vue': {
      routes:
        | '/system/tenant-isolation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/system/user-group/index.vue': {
      routes:
        | '/system/user-group/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/tool/code/index.vue': {
      routes:
        | '/tool/code/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/tool/dict/index.vue': {
      routes:
        | '/tool/dict/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/tool/file/index.vue': {
      routes:
        | '/tool/file/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/tool/gen-template/index.vue': {
      routes:
        | '/tool/gen-template/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/approval-log/index.vue': {
      routes:
        | '/workflow/approval-log/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/cc/index.vue': {
      routes:
        | '/workflow/cc/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/center/done/index.vue': {
      routes:
        | '/workflow/center/done/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/center/initiated/index.vue': {
      routes:
        | '/workflow/center/initiated/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/center/todo/index.vue': {
      routes:
        | '/workflow/center/todo/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/definition/index.vue': {
      routes:
        | '/workflow/definition/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/definition/editor/index.vue': {
      routes:
        | '/workflow/definition/editor/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workflow/delegate/index.vue': {
      routes:
        | '/workflow/delegate/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workspace/index.vue': {
      routes:
        | '/workspace/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/views/workspace/render.tsx': {
      routes:
        | '/workspace/render'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
