/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/center/': RouteRecordInfo<
      '/account/center/',
      '/account/center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/account/settings/': RouteRecordInfo<
      '/account/settings/',
      '/account/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/table-pagination-test': RouteRecordInfo<
      '/demo/table-pagination-test',
      '/demo/table-pagination-test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/micro-app/SubAppView': RouteRecordInfo<
      '/micro-app/SubAppView',
      '/micro-app/SubAppView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register/': RouteRecordInfo<
      '/register/',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/micro-app/': RouteRecordInfo<
      '/system/micro-app/',
      '/system/micro-app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/settings/': RouteRecordInfo<
      '/system/settings/',
      '/system/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/account/center/index.vue': {
      routes:
        | '/account/center/'
      views:
        | never
    }
    'src/views/account/settings/index.vue': {
      routes:
        | '/account/settings/'
      views:
        | never
    }
    'src/views/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/views/demo/table-pagination-test.vue': {
      routes:
        | '/demo/table-pagination-test'
      views:
        | never
    }
    'src/views/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/views/micro-app/SubAppView.vue': {
      routes:
        | '/micro-app/SubAppView'
      views:
        | never
    }
    'src/views/register/index.vue': {
      routes:
        | '/register/'
      views:
        | never
    }
    'src/views/system/micro-app/index.vue': {
      routes:
        | '/system/micro-app/'
      views:
        | never
    }
    'src/views/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/views/system/settings/index.vue': {
      routes:
        | '/system/settings/'
      views:
        | never
    }
    'src/views/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
