import type { MenuConfig } from '#/menu'

export const frontendMenus: MenuConfig[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    title: '仪表盘',
    icon: 'carbon:dashboard',
    component: '@/views/dashboard/index.vue',
    keepAlive: true,
  },
  {
    path: '/account',
    name: 'Account',
    title: '个人中心',
    icon: 'carbon:user-avatar',
    children: [
      {
        path: 'center',
        name: 'AccountCenter',
        title: '个人中心',
        component: '@/views/account/center/index.vue',
        keepAlive: true,
      },
      {
        path: 'settings',
        name: 'AccountSettings',
        title: '账户设置',
        component: '@/views/account/settings/index.vue',
        keepAlive: true,
      },
    ],
  },
  {
    path: '/components',
    name: 'Components',
    title: '组件',
    icon: 'carbon:code',
    children: [
      {
        path: 'basic',
        name: 'Basic',
        title: '基础组件',
        icon: 'carbon:application',
        component: '@/views/components/basic/index.vue',
      },
      {
        path: 'form',
        name: 'Form',
        title: 'Form',
        icon: 'carbon:document',
        children: [
          {
            path: 'basic',
            name: 'FormBasic',
            title: '基础表单',
            component: '@/views/components/form/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'validation',
            name: 'FormValidation',
            title: '表单验证',
            component: '@/views/components/form/validation/index.vue',
            keepAlive: true,
          },
          {
            path: 'custom-component',
            name: 'FormCustomComponent',
            title: '自定义组件',
            component: '@/views/components/form/custom-component/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'table',
        name: 'Table',
        title: 'Table',
        icon: 'carbon:table',
        children: [
          {
            path: 'basic',
            name: 'TableBasic',
            title: '基础表格',
            component: '@/views/components/table/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'animation',
            name: 'TableAnimation',
            title: '动画表格',
            component: '@/views/components/table/animation/index.vue',
            keepAlive: true,
          },
          {
            path: 'relative-time',
            name: 'TableRelativeTime',
            title: '相对时间',
            component: '@/views/components/table/relative-time/index.vue',
            keepAlive: true,
          },
          {
            path: 'count-to',
            name: 'TableCountTo',
            title: '数字动画',
            component: '@/views/components/table/count-to/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'tree',
        name: 'Tree',
        title: 'Tree',
        icon: 'carbon:tree-view',
        component: '@/views/components/tree/index.vue',
      },
      {
        path: 'scroll',
        name: 'Scroll',
        title: '滚动组件',
        icon: 'carbon:scroll-horizontal',
        children: [
          {
            path: 'basic',
            name: 'ScrollBasic',
            title: '基础滚动',
            component: '@/views/components/scroll/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'modal',
            name: 'ScrollModal',
            title: '弹窗扩展',
            component: '@/views/components/scroll/modal/index.vue',
            keepAlive: true,
          },
          {
            path: 'drawer',
            name: 'ScrollDrawer',
            title: '抽屉扩展',
            component: '@/views/components/scroll/drawer/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'detail',
        name: 'Detail',
        title: '详情组件',
        icon: 'carbon:document-view',
        component: '@/views/components/detail/index.vue',
      },
      {
        path: 'qrcode',
        name: 'QRCode',
        title: '二维码组件',
        icon: 'carbon:qr-code',
        component: '@/views/components/qrcode/index.vue',
      },
      {
        path: 'password',
        name: 'Password',
        title: '密码强度组件',
        icon: 'carbon:password',
        component: '@/views/components/password/index.vue',
      },
      {
        path: 'upload',
        name: 'Upload',
        title: '上传组件',
        icon: 'carbon:upload',
        component: '@/views/components/upload/index.vue',
      },
      {
        path: 'image-crop',
        name: 'ImageCrop',
        title: '图片裁剪',
        icon: 'carbon:crop',
        component: '@/views/components/table/image-crop/index.vue',
      },
      {
        path: 'icon-picker',
        name: 'IconPicker',
        title: '图标选择器',
        icon: 'carbon:color-palette',
        component: '@/views/components/icon-picker/index.vue',
      },
      {
        path: 'loading',
        name: 'Loading',
        title: 'Loading',
        icon: 'carbon:circle-dash',
        component: '@/views/components/loading/index.vue',
      },
      {
        path: 'card-list',
        name: 'CardList',
        title: '卡片列表',
        icon: 'carbon:grid',
        component: '@/views/components/card-list/index.vue',
      },
    ],
  },
  {
    path: '/micro-app',
    name: 'MicroApp',
    title: '微前端',
    icon: 'carbon:cloud-app',
    children: [
      {
        path: 'sub-app-1',
        name: 'SubApp1',
        title: '子应用1',
        icon: 'carbon:app',
        microApp: {
          name: 'sub-app-1',
          url: 'http://localhost:9090',
          baseroute: '/micro-app/sub-app-1',
          keepAlive: true,
        },
      },
      {
        path: 'sub-app-2',
        name: 'SubApp2',
        title: '子应用2',
        icon: 'carbon:app-connect',
        microApp: {
          name: 'sub-app-2',
          url: 'http://localhost:9091',
          baseroute: '/micro-app/sub-app-2',
          keepAlive: true,
        },
      },
    ],
  },
  {
    path: '/system',
    name: 'System',
    title: '系统设置',
    icon: 'carbon:settings',
    children: [
      {
        path: 'settings',
        name: 'SystemSettings',
        title: '配置管理',
        component: '@/views/system/settings/index.vue',
        keepAlive: true,
      },
    ],
  },
]