import type { MenuConfig } from '#/menu'

export const frontendMenus: MenuConfig[] = [
  // ==================== 数据看板 ====================
  {
    path: '/dashboard',
    name: 'Dashboard',
    title: '数据看板',
    icon: 'carbon:dashboard',
    redirect: '/dashboard/analysis',
    children: [
      {
        path: '/screen/monitor',
        name: 'ScreenMonitor',
        title: '实时监控大屏',
        icon: 'carbon:chart-line-data',
        isExternal: true,
        keepAlive: false,
      },
      {
        path: 'analysis',
        name: 'Analysis',
        title: '分析面板',
        icon: 'carbon:data-vis-4',
        component: '@/views/dashboard/analysis/index.vue',
        keepAlive: true,
      },
    ],
  },
  // ==================== 系统设置 ====================
  {
    path: '/system',
    name: 'System',
    title: '系统设置',
    icon: 'carbon:settings',
    children: [
      {
        path: 'settings',
        name: 'SystemSettings',
        title: '配置管理',
        component: '@/views/system/settings/index.vue',
        keepAlive: true,
      },
      {
        path: 'user',
        name: 'SystemUser',
        title: '用户管理',
        component: '@/views/system/user/index.vue',
        keepAlive: true,
      },
      {
        path: 'role',
        name: 'SystemRole',
        title: '角色管理',
        component: '@/views/system/role/index.vue',
        keepAlive: true,
      },
      {
        path: 'dept',
        name: 'SystemDept',
        title: '部门管理',
        component: '@/views/system/dept/index.vue',
        keepAlive: true,
      },
      {
        path: 'post',
        name: 'SystemPost',
        title: '岗位管理',
        component: '@/views/system/post/index.vue',
        keepAlive: true,
      },
      {
        path: 'dict',
        name: 'SystemDict',
        title: '字典管理',
        component: '@/views/system/dict/index.vue',
        keepAlive: true,
      },
      {
        path: 'menu',
        name: 'SystemMenu',
        title: '菜单管理',
        component: '@/views/system/menu/index.vue',
        keepAlive: true,
      },
      {
        path: 'online',
        name: 'SystemOnline',
        title: '在线用户',
        component: '@/views/system/online/index.vue',
        keepAlive: true,
      },
      {
        path: 'notice',
        name: 'SystemNotice',
        title: '消息通知',
        component: '@/views/system/notice/index.vue',
        keepAlive: true,
      },
      {
        path: 'file',
        name: 'SystemFile',
        title: '文件中心',
        component: '@/views/system/file/index.vue',
        keepAlive: true,
      },
    ],
  },
  // ==================== 日志管理（独立一级菜单）====================
  {
    path: '/logs',
    name: 'Logs',
    title: '日志管理',
    icon: 'carbon:catalog',
    children: [
      {
        path: 'operation',
        name: 'LogsOperation',
        title: '操作日志',
        icon: 'carbon:activity',
        component: '@/views/system/log/index.vue',
        keepAlive: true,
      },
      {
        path: 'login',
        name: 'LogsLogin',
        title: '登录日志',
        icon: 'carbon:user-multiple',
        component: '@/views/system/login-log/index.vue',
        keepAlive: true,
      },
    ],
  },
  // ==================== 安全中心（独立一级菜单）====================
  {
    path: '/security',
    name: 'Security',
    title: '安全中心',
    icon: 'carbon:security',
    children: [
      {
        path: 'dashboard',
        name: 'SecurityDashboard',
        title: '安全审计仪表盘',
        icon: 'carbon:dashboard',
        component: '@/views/security/dashboard/index.vue',
        keepAlive: true,
      },
    ],
  },
  // ==================== 组件（示例/展示用途）====================
  {
    path: '/components',
    name: 'Components',
    title: '组件',
    icon: 'carbon:code',
    children: [
      {
        path: 'basic',
        name: 'Basic',
        title: '基础组件',
        icon: 'carbon:application',
        component: '@/views/components/basic/index.vue',
      },
      {
        path: 'form',
        name: 'Form',
        title: 'Form',
        icon: 'carbon:document',
        children: [
          {
            path: 'basic',
            name: 'FormBasic',
            title: '基础表单',
            component: '@/views/components/form/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'validation',
            name: 'FormValidation',
            title: '表单验证',
            component: '@/views/components/form/validation/index.vue',
            keepAlive: true,
          },
          {
            path: 'custom-component',
            name: 'FormCustomComponent',
            title: '自定义组件',
            component: '@/views/components/form/custom-component/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'table',
        name: 'Table',
        title: 'Table',
        icon: 'carbon:table',
        children: [
          {
            path: 'basic',
            name: 'TableBasic',
            title: '基础表格',
            component: '@/views/components/table/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'animation',
            name: 'TableAnimation',
            title: '动画表格',
            component: '@/views/components/table/animation/index.vue',
            keepAlive: true,
          },
          {
            path: 'relative-time',
            name: 'TableRelativeTime',
            title: '相对时间',
            component: '@/views/components/table/relative-time/index.vue',
            keepAlive: true,
          },
          {
            path: 'count-to',
            name: 'TableCountTo',
            title: '数字动画',
            component: '@/views/components/table/count-to/index.vue',
            keepAlive: true,
          },
          {
            path: 'tree-table',
            name: 'TableTreeTable',
            title: '树表格',
            component: '@/views/components/table/tree-table/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'tree',
        name: 'Tree',
        title: 'Tree',
        icon: 'carbon:tree-view',
        component: '@/views/components/tree/index.vue',
      },
      {
        path: 'scroll',
        name: 'Scroll',
        title: '滚动组件',
        icon: 'carbon:scroll-horizontal',
        children: [
          {
            path: 'basic',
            name: 'ScrollBasic',
            title: '基础滚动',
            component: '@/views/components/scroll/basic/index.vue',
            keepAlive: true,
          },
          {
            path: 'modal',
            name: 'ScrollModal',
            title: '弹窗扩展',
            component: '@/views/components/scroll/modal/index.vue',
            keepAlive: true,
          },
          {
            path: 'drawer',
            name: 'ScrollDrawer',
            title: '抽屉扩展',
            component: '@/views/components/scroll/drawer/index.vue',
            keepAlive: true,
          },
        ],
      },
      {
        path: 'detail',
        name: 'Detail',
        title: '详情组件',
        icon: 'carbon:document-view',
        component: '@/views/components/detail/index.vue',
      },
      {
        path: 'qrcode',
        name: 'QRCode',
        title: '二维码组件',
        icon: 'carbon:qr-code',
        component: '@/views/components/qrcode/index.vue',
      },
      {
        path: 'password',
        name: 'Password',
        title: '密码强度组件',
        icon: 'carbon:password',
        component: '@/views/components/password/index.vue',
      },
      {
        path: 'upload',
        name: 'Upload',
        title: '上传组件',
        icon: 'carbon:upload',
        component: '@/views/components/upload/index.vue',
      },
      {
        path: 'image-crop',
        name: 'ImageCrop',
        title: '图片裁剪',
        icon: 'carbon:crop',
        component: '@/views/components/table/image-crop/index.vue',
      },
      {
        path: 'icon-picker',
        name: 'IconPicker',
        title: '图标选择器',
        icon: 'carbon:color-palette',
        component: '@/views/components/icon-picker/index.vue',
      },
      {
        path: 'loading',
        name: 'Loading',
        title: 'Loading',
        icon: 'carbon:circle-dash',
        component: '@/views/components/loading/index.vue',
      },
      {
        path: 'card-list',
        name: 'CardList',
        title: '卡片列表',
        icon: 'carbon:grid',
        component: '@/views/components/card-list/index.vue',
      },
      {
        path: 'video',
        name: 'Video',
        title: '视频播放器',
        icon: 'carbon:video',
        component: '@/views/components/video/index.vue',
        keepAlive: true,
      },
      {
        path: 'vueuse',
        name: 'Vueuse',
        title: 'VueUse Hooks',
        icon: 'carbon:tool-kit',
        component: '@/views/components/vueuse/index.vue',
        keepAlive: true,
      },
      {
        path: 'editor',
        name: 'Editor',
        title: '编辑器',
        icon: 'carbon:edit',
        children: [
          {
            path: 'markdown',
            name: 'EditorMarkdown',
            title: 'Markdown编辑器',
            component: '@/views/components/editor/markdown/index.vue',
            keepAlive: true,
          },
          {
            path: 'rich-text',
            name: 'EditorRichText',
            title: '富文本编辑器',
            component: '@/views/components/editor/rich-text/index.vue',
            keepAlive: true,
          },
        ],
      },
      // {
      //   path: 'form-designer',
      //   name: 'FormDesigner',
      //   title: '表单设计器',
      //   icon: 'carbon:pen-tool',
      //   component: '@/views/components/form-designer/index.vue',
      // },
    ],
  },
]
