import type {
  AppSetting,
  ComponentSize,
  LayoutMode,
  NotificationPosition,
  RouteMode,
  ThemeMode,
  ThemeStyle,
  TransitionEffect,
} from '#/app'

export type {
  AppSetting,
  ComponentSize,
  LayoutMode,
  NotificationPosition,
  RouteMode,
  ThemeMode,
  ThemeStyle,
  TransitionEffect,
}

export const DEFAULT_SETTING: AppSetting = {
  theme: 'light',
  themeStyle: 'default',
  componentSize: 'medium',
  layout: 'vertical',
  darkSidebar: false,
  darkHeader: false,
  colorWeak: false,
  grayMode: false,
  notificationPosition: 'topRight',
  sidebarWidth: 210,
  showBreadcrumb: true,
  showTabs: true,
  tabShowIcon: true,
  showFooter: true,
  enableWaterRipple: true,
  transitionEffect: 'fade-slide',
  enableWatermark: false,
  watermarkContent: import.meta.env.VITE_APP_TITLE || 'Admin',
  sidebarCollapsed: false,
  primaryColor: '#1677ff',
  borderRadius: 0.5,
  fontSize: 14,
  menuAccordion: true,
  hideBreadcrumbWhenOnlyOne: true,
  showBreadcrumbIcon: true,
  /* ---------- 小部件 ---------- */
  widgetNotice: true,
  widgetFullscreen: true,
  widgetTheme: true,
  widgetTimezone: false,
  widgetLogout: true,
  widgetSearch: true,
  widgetPreferences: true,
  showCopyright: true,
  copyrightCompany: import.meta.env.VITE_APP_TITLE || 'Antdv Admin',
  copyrightIcp: '',
  /* ---------- 通用 ---------- */
  timezone: 'Asia/Shanghai',
  showProgressBar: true,
  showLoading: true,
  locale: 'zh-CN',
}

export * from './theme'
