export const LAYOUT_HEADER_HEIGHT = 48
export const LAYOUT_TABS_HEIGHT = 40
export const LAYOUT_FOOTER_HEIGHT = 32
export const LAYOUT_SIDEBAR_COLLAPSED_WIDTH = 80

export const LAYOUT_HEADER_AND_TABS_HEIGHT = LAYOUT_HEADER_HEIGHT + LAYOUT_TABS_HEIGHT
